Leave/Rejoin notification
cse112-sp24-group12/cse112-sp24-group12 pull request #59
Opened 2024-05-23 01:34 UTC by arjunghoshal

Resolved #50

2024-05-23 06:14 UTC, Luke-Sheltraw requested changes

2024-05-23 06:14 UTC, Luke-Sheltraw commented on source/server/main.js
> +  if (!attemptRejoinStatus) {
an if/else statement should probably have the negation as the else clause instead of the if clause, for clarity's sake

2024-05-23 06:31 UTC, arjunghoshal commented on source/server/main.js
> +  let profile = structuredClone(webSocketConnection.profile);
Sounds good to me, I'll implement that with the disconnect/leave stuff. Should we update the actions flowchart to add the new action?

2024-05-23 06:35 UTC, Luke-Sheltraw commented on source/server/main.js
> +  let profile = structuredClone(webSocketConnection.profile);
There are actually a few actions that need to be added to the flow chart lol

2024-05-26 21:03 UTC, Luke-Sheltraw approved these changes
Thanks for making the changes

2024-05-26 21:03 UTC, merged