Settings
cse112-sp24-group12/cse112-sp24-group12 pull request #97
Opened 2024-06-05 22:53 UTC by ngngo0

Closes [#54](https://github.com/cse112-sp24-group12/cse112-sp24-group12/issues/54)

2024-06-07 20:22 UTC, Luke-Sheltraw requested changes

2024-06-07 20:22 UTC, Luke-Sheltraw commented on source/client/scripts/settings.js
> +  if (
this function is HUGE

2024-06-07 22:43 UTC, ngngo0 commented on source/client/scripts/settings.js
> +function saveVolume(volumeEl, setVolumeCallbackFn) {
honestly..... i dont remember changing this 😂

2024-06-07 23:02 UTC, ngngo0 commented on source/client/scripts/settings.js
> +  if (
you have a point.......

2024-06-09 19:41 UTC, Luke-Sheltraw approved these changes

2024-06-09 19:41 UTC, merged